"use client";

/**
 * A curated icon registry. Named imports keep the bundle honest — importing the
 * whole of lucide-react for a dynamic lookup would ship thousands of unused paths.
 */
import {
  Activity,
  AlarmClock,
  AlarmClockCheck,
  ArrowDownRight,
  ArrowRight,
  ArrowUpRight,
  BarChart3,
  Bell,
  BookOpen,
  Boxes,
  Brain,
  Calendar,
  CalendarDays,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleDot,
  ClipboardCheck,
  Clock,
  Command,
  Compass,
  Download,
  Dumbbell,
  Flag,
  Flame,
  GlassWater,
  Gauge,
  Home,
  Import,
  Info,
  Layers,
  LineChart,
  ListChecks,
  Loader2,
  Lock,
  MapPin,
  Minus,
  MonitorSmartphone,
  MoonStar,
  Mountain,
  Move,
  PenLine,
  Play,
  Plus,
  RotateCcw,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Smartphone,
  SmartphoneNfc,
  Sparkles,
  Sunrise,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Users,
  Volume2,
  VolumeX,
  Wind,
  X,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type React from "react";

export const ICONS = {
  Activity,
  AlarmClock,
  AlarmClockCheck,
  ArrowDownRight,
  ArrowRight,
  ArrowUpRight,
  BarChart3,
  Bell,
  BookOpen,
  Boxes,
  Brain,
  Calendar,
  CalendarDays,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleDot,
  ClipboardCheck,
  Clock,
  Command,
  Compass,
  Download,
  Dumbbell,
  Flag,
  Flame,
  GlassWater,
  Gauge,
  Home,
  Import,
  Info,
  Layers,
  LineChart,
  ListChecks,
  Loader2,
  Lock,
  MapPin,
  Minus,
  MonitorSmartphone,
  MoonStar,
  Mountain,
  Move,
  PenLine,
  Play,
  Plus,
  RotateCcw,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Smartphone,
  SmartphoneNfc,
  Sparkles,
  Sunrise,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Users,
  Volume2,
  VolumeX,
  Wind,
  X,
  Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  strokeWidth = 1.6,
  ...props
}: React.SVGProps<SVGSVGElement> & { name: string; strokeWidth?: number }) {
  const Cmp = ICONS[name as IconName] ?? CircleDot;
  return <Cmp strokeWidth={strokeWidth} aria-hidden {...props} />;
}
