/**
 * Elite Life OS — domain types.
 *
 * Everything the operating system knows about a life lives in `LifeState`.
 * It is a single serialisable object: one localStorage key, one version number,
 * one migration path. Derived numbers (scores, streaks, momentum) are never
 * stored — they are computed from the day log in `engine.ts` so the history is
 * always the single source of truth.
 */

/** `YYYY-MM-DD` in the user's local timezone. */
export type ISODate = string;
/** `HH:MM` 24h, local. */
export type Clock = string;

export type HabitId =
  | "win-tomorrow"
  | "protect-morning"
  | "journal"
  | "learn"
  | "environment"
  | "measure"
  | "momentum"
  | "choose-hard";

export interface HabitDef {
  id: HabitId;
  index: number;
  name: string;
  verb: string;
  principle: string;
  description: string;
  /** Lucide icon name, resolved in the UI layer. */
  icon: string;
  /** Hue used for this habit's accent, in degrees. */
  hue: number;
  /** Where the habit is actioned in the app. */
  href: string;
  /** Which part of the day this habit belongs to. */
  phase: "night" | "morning" | "day";
  /** Weight in the daily score (all equal by default, kept for tuning). */
  weight: number;
}

export interface Priority {
  id: string;
  title: string;
  done: boolean;
  /** Set when completed, for the timeline. */
  completedAt?: string;
}

export interface JournalEntry {
  brainDump: string;
  gratitude: [string, string, string];
  completedAt?: string;
}

export interface LearningEntry {
  pages: number;
  nugget: string;
  apply: string;
  teach: string;
  completedAt?: string;
}

export interface Debrief {
  wentWell: string;
  didnt: string;
  learned: string;
  change: string;
  completedAt?: string;
}

/** One row of the life log. Absent days simply never happened. */
export interface DayRecord {
  date: ISODate;
  habits: Partial<Record<HabitId, boolean>>;
  /** Morning routine step id -> `HH:MM` the step was completed. */
  morning: Record<string, Clock>;
  wakeTarget?: Clock;
  wakeActual?: Clock;
  bedTarget?: Clock;
  bedActual?: Clock;
  priorities: Priority[];
  journal?: JournalEntry;
  learning?: LearningEntry;
  /** North Star value recorded for the day. */
  northStar?: number;
  debrief?: Debrief;
  /** Challenge milestones completed on this day. */
  milestones?: string[];
  xp: number;
  /** True for rows generated by the demo seed rather than lived. */
  seeded?: boolean;
  /**
   * Epoch ms of the last edit to this day, stamped on every write. Sync merges
   * day by day and keeps the newer row, so a morning logged on one device and
   * an evening logged on another both survive.
   */
  updatedAt?: number;
}

export interface NorthStar {
  label: string;
  unit: string;
  /** `prefix` renders €8,420, `suffix` renders 8,420 km. */
  unitPosition: "prefix" | "suffix";
  target: number;
  /** Direction of a good move. */
  direction: "up" | "down";
}

export interface Milestone {
  id: string;
  label: string;
  /** 0–1 position along the path. */
  at: number;
  done: boolean;
  doneOn?: ISODate;
}

export interface Challenge {
  title: string;
  why: string;
  startDate: ISODate;
  endDate: ISODate;
  milestones: Milestone[];
  completedAt?: string;
}

export interface Book {
  title: string;
  author: string;
  totalPages: number;
  dailyTarget: number;
  startedOn: ISODate;
  finishedOn?: ISODate;
}

export type PersonImpact = "raises" | "neutral" | "drains";

export interface Person {
  id: string;
  name: string;
  relation: string;
  impact: PersonImpact;
  note: string;
  /** Last time the user deliberately invested in (or created distance from) this relationship. */
  lastReviewed?: ISODate;
}

export type PlaceStatus = "optimized" | "needs-work" | "hostile";

export interface Place {
  id: string;
  name: string;
  category: "physical" | "digital";
  status: PlaceStatus;
  note: string;
}

export interface EnvChange {
  id: string;
  /** `easy` = make a good habit easier. `hard` = make a bad habit harder. */
  kind: "easy" | "hard";
  text: string;
  done: boolean;
  createdOn: ISODate;
}

export interface Settings {
  wakeTime: Clock;
  bedTime: Clock;
  /** Minutes of protected morning after wake-up. */
  protectedMinutes: number;
  windDownMinutes: number;
  alarmsEnabled: boolean;
  wakeAlarmEnabled: boolean;
  bedAlarmEnabled: boolean;
  sound: boolean;
  volume: number;
  theme: "dark" | "light";
  accent: AccentId;
  reducedMotion: boolean;
  showDemoHistory: boolean;
  notificationsAsked: boolean;
}

export type AccentId = "aurora" | "ember" | "signal" | "violet" | "ice";

export interface CoachMessage {
  id: string;
  role: "user" | "coach";
  content: string;
  /** Which engine produced the answer. Never claim AI when it was local. */
  source?: "local" | "model";
  at: string;
}

export interface Profile {
  name: string;
  mission: string;
}

export interface LifeState {
  version: number;
  profile: Profile;
  settings: Settings;
  days: Record<ISODate, DayRecord>;
  northStar: NorthStar;
  challenge: Challenge;
  book: Book;
  people: Person[];
  places: Place[];
  envChanges: EnvChange[];
  coach: CoachMessage[];
  /** Set once, so the demo history is only ever generated on a fresh install. */
  seededAt?: string;
  createdAt: string;
  /**
   * Epoch ms of the last edit to anything outside `days` — profile, settings,
   * north star, challenge, book, people, places, environment. Those are single
   * values rather than a log, so a merge cannot combine them: the side edited
   * more recently wins, and this is how that is decided.
   */
  touchedAt?: number;
}

export const STORAGE_KEY = "elite-life-os:v1";
/**
 * 2 — the seeded sample people, places and environment changes shipped by v1 are
 * removed on load. Nothing invented survives an upgrade.
 */
export const STATE_VERSION = 2;
